name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check code practices with ESLint
        run: npm run lint

      - name: Format code with Prettier
        run: npm run format

      - name: Remove console.log statements
        run: |
          find . -name "*.js" -exec sed -i '/console\.log(/d' {} \;

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || git commit -m "Apply code formatting and remove console.log statements"

      - name: Push changes
        if: success()
        run: |
          git push origin main

      - name: Run tests
        run: npm test

      - name: Build app
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      # print current path
      - name: Print current path
        run: pwd

      # print all the files in the current folder
      - name: List files in current folder
        run: ls -a

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
